name: Test

on:
  pull_request:
  push:
    branches:
      - dev
      - main

permissions: {}

jobs:
  test:
    name: Test (Python 3.14)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@main
        with:
          python-version: "3.14"

      - name: Install systemd development files
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends libsystemd-dev

      - name: Run checks
        run: |
          uv run --locked ruff format --check
          uv run ruff check
          uv run ty check
          uv build --all-packages --no-create-gitignore --no-sources

      - name: Run tests
        run: uv run pytest
